# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(647, 346)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 90, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.labelReturn = QtWidgets.QLabel(self.centralwidget)
        self.labelReturn.setGeometry(QtCore.QRect(90, 180, 441, 91))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelReturn.setFont(font)
        self.labelReturn.setText("")
        self.labelReturn.setObjectName("labelReturn")
        self.inputValidate = QtWidgets.QLineEdit(self.centralwidget)
        self.inputValidate.setGeometry(QtCore.QRect(140, 90, 391, 26))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        self.inputValidate.setFont(font)
        self.inputValidate.setObjectName("inputValidate")
        self.btnValidate = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidate.setGeometry(QtCore.QRect(540, 90, 93, 29))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        self.btnValidate.setFont(font)
        self.btnValidate.setObjectName("btnValidate")
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setGeometry(QtCore.QRect(540, 30, 93, 29))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        self.btnGenerate.setFont(font)
        self.btnGenerate.setObjectName("btnGenerate")
        self.inputGenerate = QtWidgets.QLineEdit(self.centralwidget)
        self.inputGenerate.setGeometry(QtCore.QRect(120, 30, 411, 26))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        self.inputGenerate.setFont(font)
        self.inputGenerate.setObjectName("inputGenerate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "cnpjValidator"))
        self.label.setText(_translate("MainWindow", "VERIFICAR CNPJ"))
        self.label_2.setText(_translate("MainWindow", "GERAR CNPJ"))
        self.btnValidate.setText(_translate("MainWindow", "VALIDAR"))
        self.btnGenerate.setText(_translate("MainWindow", "GERAR"))
